---

name : "default"

# デバッグ
debug : True
debug_data_len : 1000
debug_max_epoch : 200
debug_iter : 0

# checkpointから再開する場合
check_point_start : True
start_ckpt_path : "~/lip2sp_pytorch/parallelwavegan/check_point/default/lip_nn_gray_08_50/2022:11:29_21-57-23/mspec80_40.ckpt"

# face or lip
face_or_lip : "lip_nn_gray_08_50"

# 学習したモデルのパラメータを保存するディレクトリまでのパス
save_path : "~/lip2sp_pytorch/parallelwavegan/result/default/train"

# check point path
ckpt_path : "~/lip2sp_pytorch/parallelwavegan/check_point/default"
ckpt_step : 10

# data path
lip_pre_loaded_path_nn_train_gray_08_50 : "~/dataset/lip/np_files/lip_cropped_nn_gray_0.8_50/train"
lip_pre_loaded_path_nn_val_gray_08_50 : "~/dataset/lip/np_files/lip_cropped_nn_gray_0.8_50/val"

# 使用するコーパス
corpus : ["ATR", "BASIC5000", "balanced"]
# corpus : ["ATR"]

# 使用する話者
speaker : ["F01_kablab"]
# speaker : ["F01_kablab", "F02_kablab", "M01_kablab", "M04_kablab"]

# max_epoch
max_epoch : 600

# data augmentationの有無
# 見た目変換系
use_color_jitter : False
use_blur : False
use_horizontal_flip : False
use_pad : False
use_rotation : False
use_random_crop : False

# 空間領域にランダムマスキング
use_spatial_masking : False
spatial_divide_factor : 4
n_spatial_mask : 4

# 再生速度変換
use_time_augment : False
time_augment_rate : 20    # (100 - rate)から(100 + rate)の範囲で再生速度を変更

# 動画のフレームをランダムマスキング
use_frame_masking : False
frame_masking_rate : 40

# 動画の連続したフレームをある程度まとめてマスキング
use_segment_masking : False
which_seg_mask : "seg_mean"
segment_masking_length : 20

# dataloader
batch_size : 4
num_workers : 4

# optimizer
lr_gen : 0.0001
lr_disc : 0.00005
beta_1 : 0.9
beta_2 : 0.999
eps : 1.0e-6
weight_decay : 1.0e-6

# scheduler
multi_lr_decay_step : [200, 400]   # 学習率を変更するepoch
lr_decay : 0.999

# gradient clipping
max_norm : 3.0

# stft loss parameter
n_fft_list : [320, 640, 1280]
hop_length_list : [80, 160, 320]
win_length_list : [320, 640, 1280]

# lossの重みづけ
stft_loss_weight : 1.0
gan_loss_weight : 4.0