# @package _group_

# データを置いているディレクトリまでのパス
train_path : "/users/minami/dataset/train"
test_path : "/users/minami/dataset/test"

# 学習したモデルのパラメータを保存するディレクトリまでのパス
train_save_path : "/Users/minami/Documents/python/lip2sp_pytorch/mlruns/2/5d13447ad7e440a4a5ed3783859e38e3/artifacts/model_state_dict"

# generate.pyを実行したときのデータを保存するディレクトリまでのパス
generate_save_path : "/users/minami/result/generate"

# 平均、標準偏差を保存するディレクトリまでのパス
train_mean_std_path : "/users/minami/dataset/np_files/mean_std/train"
test_mean_std_path : "/users/minami/dataset/np_files/mean_std/test"

# 口唇動画、音響特徴量を保存するディレクトリまでのパス
train_pre_loaded_path : "/users/minami/dataset/np_files/data/train"
test_pre_loaded_path : "/users/minami/dataset/np_files/data/test"

# mlflowの保存先
experiment_name : "test"

# dropout
dropout : 0.1

# global condition
use_gc : False

# 学習方法（"tf" or "ss"）
# tf : teacher forcing
# ss : scheduled sampling
training_method : "ss"

# parameter for scheduled sampling
num_passes : 1     # 繰り返し回数
mixing_prob : 0.5  # 混合率

# dataloader
batch_size : 5
num_workers : 0

# optimizer
lr : 0.001
beta_1 : 0.9
beta_2 : 0.999

# training
max_iter : 5
max_epoch : 1

# test lossを計算する間隔
display_test_loss_step : 4