name: 'main'
max_epoch: 50
batch_size: 1024
learning_rate: 1.0e-3
hidden_channels: 256
num_workers: 16
data_dir: './'
train_ratio: 0.8
seed: 42
early_stopping_patience: 3
monitoring_metric: 'val_loss'
monitoring_mode: 'min'
save_checkpoint_every_n_epochs: 1
save_checkpoint_top_k: 5
swa_lrs: 1.0e-2
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
log_every_n_steps: 10
precision: 'bf16-mixed'
accumulate_grad_batches: 1
gradient_clip_val: 3.0
gradient_clip_algorithm: 'norm'