defaults:
  - model: mspec80_trans_taco
  - train: transformer_96_desk
  - test : trans_taco_desk
  - wandb_conf : default
tag: "tts_test"
model_path: None
stop_weight: 1.0
from_tts: /home/naoaki/lip2sp_pytorch_all/lip2sp_920_re/check_point/tts/test/mspec80_92.ckpt
