defaults:
  - model: mspec80_trans_taco_from_tts
  - train: transformer_96
  - test : trans_taco_desk
  - wandb_conf : default
  
  - from_tts : tts_path
tag: "tts_test"
model_path: None
stop_weight: 1.0