defaults:
  - model: mspec80_trans_taco_from_tts
  - train: transformer_96
  - test : trans_taco_desk
  - wandb_conf : default
tag: "tts_test"
model_path: None
stop_weight: 1.0
from_tts: /home/usr1/q70261a/lip2sp_pytorch_all/lip2sp_920_re/check_point/tts/2023:10:05_23-04-58__jsut_BASIC5000/mspec80_228.ckpt