defaults:
  - model: mspec80_trans_taco
  - train: transformer_96_all_desk
  - test : trans_taco_desk
  - wandb_conf : default

  - from_tts : tts_path
tag: "tts_test"
model_path: /home/naoaki/lip2sp_pytorch_all/lip2sp_920_re/check_point/test/mspec80_330.ckpt
stop_weight: 1.0
#from_tts: /home/usr1/q70261a/lip2sp_pytorch_all/lip2sp_920_re/check_point/tts/2023:10:03_22-26-45__revise_stop_token/mspec80_108.ckpt

method : 'tf'