hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - model=mspec,world
    - model.n_layers=1,2
    - model.n_head=2,4
  job:
    name: train
    chdir: null
    override_dirname: model.n_head=2,4,model.n_layers=1,2,model=mspec,world
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.2.0
    version_base: '1.1'
    cwd: /Users/minami/Documents/python/lip2sp_pytorch
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /Users/minami/Documents/python/lip2sp_pytorch/conf
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      train: train_1
      model: world
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
model:
  train_path: /users/minami/dataset/train
  test_path: /users/minami/dataset/test
  fps: 50
  video_channels: 3
  sampling_rate: 16000
  n_fft: 1024
  hop_length: 160
  win_length: 640
  f_min: 0
  f_max: 7600
  n_mel_channels: 80
  gray: false
  delta: true
  frame_period: 10
  length: 300
  reduction_factor: 2
  feature_type: world
  in_channels: 5
  res_layers: 5
  glu_inner_channels: 256
  glu_layers: 4
  n_layers: 6
  d_model: 256
  n_head: 8
  which_encoder: transformer
  which_decoder: transformer
  which_d: null
  out_channels: 29
  pre_in_channels: 58
  pre_inner_channels: 32
  post_inner_channels: 512
train:
  dropout: 0.1
  use_gc: false
  training_method: ss
  num_passes: 1
  mixing_prob: 0.5
  batch_size: 5
  num_workers: 0
  lr: 0.001
  beta_1: 0.9
  beta_2: 0.999
  max_iter: 5
  max_epoch: 2
